### ISSUE TITLE
Kleur gebruik

### ISSUE THREAD

**Issue by rikschennink** [dandevri/minor-cssttr#1]
Tip, haal voorgrond en achtergrond kleur even door http://contrastchecker.com/ om te kijken of ze contrasterend genoeg zijn voor bijvoorbeeld mensen met kleurenblindheid of slechtzienden.

**Comment by dandevri** [comment]
Thanks for the tool! Using CSS variables for the color. So I am still playing around with the right colors but can easily change them with the variables.
