### ISSUE TITLE
Focus- en hover-styles

### ISSUE THREAD

**Issue by vasilisvg** [dandevri/minor-cssttr#10]
De focus- en hover-states zijn niet (overal) vormgegeven. Hierdoor lijkt de pagina nogal onactief als je er doorheen tabt of er over beweegt met je muis. Die states zijn juist superbelangrijk. Geef ze vorm. Hier kan je ook transities voor gebruiken.
Let er bij die states ook op dat ze wel zichtbaar zijn, bijvoorbeeld op het formulier: is het wel zichtbaar op de achtergrond?

**Comment by dandevri** [comment]
Added more `:focus` and `:hover` styles and transitions. Also used CSS filters to give some element slight color changes.
