### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by vasilisvg** [dandevri/minor-cssttr#11]
Stel dat de tweede persoon twee berichtjes achter elkaar had getypt. Dat zou dat met deze CSS niet zichtbaar zijn …

**Comment by vasilisvg** [comment]
Op een smal scherm gaat het ook nogal mis

**Comment by dandevri** [comment]
* Added `data=user` and `data=you` attribute. (Not classes)
* Fixed some flexbox setting for small screen
