### ISSUE TITLE
Media item

### ISSUE THREAD

**Issue by vasilisvg** [dandevri/minor-cssttr#13]
- Je hebt nu maar een visuele variant gemaakt van het media-element. Maar er zijn flink wat verschillende manieren te bedenken waarop je dit kunt laten zien. Zie bijvoorbeeld de homepage van [The Guardian](https://www.theguardian.com/international) of de linkerkolom van [de Volkskrant](http://www.volkskrant.nl). Kijk eens of je net zo'n lijst kan maken waarbij de eerste er anders uit ziet dan de rest.

**Comment by dandevri** [comment]
Added :first-child to article items.
