### ISSUE TITLE
Piture with subtitle

### ISSUE THREAD

**Issue by vasilisvg** [dandevri/minor-cssttr#15]
Dit probleem is complexer: Het plaatje moet _altijd_ helemaal zichtbaar zijn in elke viewport. Dus maximaal `100vh`, en maximaal `100vw`. Bovendien moet je ook altijd kunnen zien dat er een onderschrift is. En dit moet werken met een landscape en een portrait plaatje …
En kan je je nog herinneren hoeveel `em` breed een paragraaf maximaal mag zijn?
En hier is er iets mis met de aangeleverde HTML. Hier moet je dus wel iets aanpassen (-:

**Comment by rijkvanzanten** [comment]
🇺🇸

You could consider putting the image to the left of the text (in portrait). That way, the image will be shown full size and the text will be less wide :)

**Comment by dandevri** [comment]
🎉

Played around with the idea that @rijkvanzanten suggested. Changed the `max-width` on all articles to make sure paragraphs don't exceed the `em` width.
