### ISSUE TITLE
Al met al

### ISSUE THREAD

**Issue by vasilisvg** [dandevri/minor-cssttr#17]
Je hebt nog wel wat te doen, zo te zien. 
Kijk ook eens of je hier een *echte* site van kan maken. Lukt het je om alle elementen op een logische manier te tonen? Het mag op één pagina, maar ook op meerdere pagina's. Het onderwerp mag je natuurlijk zelf weten.

**Comment by dandevri** [comment]
Started playing around with making these components into a full site, first I wanted to focus on the components itself and made sure these where plausible.
