### ISSUE TITLE
Increase overall font-size

### ISSUE THREAD

**Issue by rijkvanzanten** [dandevri/minor-cssttr#18]
With changing the font size on the html element to lets say 145%, you'll immediately fix some long-text-line issues and make everything a little more clearer to read for the end user.

**Comment by dandevri** [comment]
That's a decent point, increased the font-size a bit but I don't want to blow up the `em` value.

**Comment by rijkvanzanten** [comment]
You van leave all the ems as is and just change the fontsize on the root element. That's the beauty of relative units 🗽
