### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by rikschennink** [dandevri/minor-cssttr#2]
Wie stuurde welk bericht, dat kan nog wat duidelijker, wellicht met kleur of locatie chat ballon. Voor inspiratie, zoek eens op Dribbble https://dribbble.com/search?q=chat

Door de kleur van het text invoer veld is de focus stijl op OSX bijna onzichtbaar geworden.

**Comment by dandevri** [comment]
Changed the background-color of the chat bubbles for more differentiation.
