### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by rikschennink** [dandevri/minor-cssttr#5]
Je zou de :checked selector in combinatie met de sibling selector kunnen gebruiken om de  checkbox van een andere stijl te voorzien (het label kan hierbij helpen).

**Comment by dandevri** [comment]
Styled the checkbox according: [CSS Secrets 6.31 - Custom Checkboxes.](http://proquestcombo.safaribooksonline.com.rps.hva.nl:2048/book/web-development/css/9781449372736/chapter-7dot-structure-and-layout/ch07lev1sec01_html#X2ludGVybmFsX0h0bWxWaWV3P3htbGlkPTk3ODE0NDkzNzI3MzYlMkZmb290bm90ZV9odG1sJnF1ZXJ5PQ==)
