### ISSUE TITLE
Specificity

### ISSUE THREAD

**Issue by rikschennink** [dandevri/minor-cssttr#7]
Let op je specificiteit (https://specificity.keegan.st) minder specifiek is beter (dan is later overriden makkelijker). Gebruik geen #id voor styling, dat weegt veel te zwaar (zie link).

**Comment by dandevri** [comment]
Started using schema used in [this](https://docs.google.com/presentation/d/1w9LDubDlfp1re_6rKsksl2xY5ijHNhMd11W1Wheyfq0/edit#slide=id.g1cd6453ffe_0_402) slide.

Also changed the ID's of the sections to classes.
