### ISSUE TITLE
witruimtes

### ISSUE THREAD

**Issue by rikschennink** [dandevri/minor-cssttr#8]
Probeer structureel dezelfde marges en paddings te gebruiken, dat maakt de interface een stuk rustiger om naar te kijken. Nu verschilt het nogal per component en per element. Laat elementen de parent uitvullen en gebruik padding en marges ipv width + percentages om breedtes te bepalen.

**Comment by dandevri** [comment]
Started using CSS variables to make padding and margin values more consistent and easy to change on many of the same elements.
